menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/volodymyr-lian/
    Rss: /atom.xml

favicon: /favicon.png
logo: /helloboy.gif

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
cloudTie:
sohucs:
    appId: cyt1jefB2
    appKey: c7ff34c4a9e32342ab8fdf52ef837615
# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
